### PR TITLE
electrum: add package

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by xeffyr** [comment]
Hmm, need to think about the best way for installing python modules. Current variant will either overwrite modules installed by user or will be overwritten by user.

It is possible to install/use modules from specific path, but will require some work.

**Comment by Grimler91** [comment]
This particular PR installs all python dependencies in the [postinst](https://github.com/Grimler91/unstable-packages/blob/094aa5f83475135fd26ad2942582c8e979c54c11/packages/electrum/build.sh#L67) script and makes sure that none of the [python dependencies are included in the deb](https://github.com/Grimler91/unstable-packages/blob/094aa5f83475135fd26ad2942582c8e979c54c11/packages/electrum/build.sh#L23) (as some of them are for x86_64), so only module that can be overwritten in this PR is electrum, and if user has installed electrum already it is unusable anyways. 

I agree that it would be nicer to put python modules in another folder tree though.

**Comment by xeffyr** [comment]
> This particular PR installs all python dependencies in the postinst script

Ah, okay. I do same for [zeronet](https://github.com/termux/unstable-packages/blob/master/packages/zeronet/installer.sh) package.

Are you sure that modules installed via pip don't do compilation of native extensions ? I did't checked this.

**Comment by Grimler91** [comment]
@xeffyr I installed electrum in a fresh termux installation to verify and no other DEPENDS (like clang or python-dev) were needed.

Other python modules might need clang and/or other packages though, so it needs to be verified for each package. Unless we specify that python-dev and clang are needed by all python packages, just in case

**Pull request merged**
