### PR TITLE
Add samba

### PR DESCRIPTION
**Pull request by qwerty12**
(~~The termux-packages submodule in this repository needs updating first - libtirrpc is missing from termux-packages, I didn't know to do it properly.~~ Thanks Grimler91 :) `libparse-yapp-perl heimdal-multidev comerr-dev` needs to be installed in the Ubuntu build host - they're all present in `setup_ubuntu.sh`.)

* I've tested Samba builds for 32-bit ARM, as well as 64-bit ARM, but I've not tested it on a 32-bit ARM device. Works fine on my 64-bit phone, though.

    * Android 32-bit ARM doesn't have a `pw_gecos` field in the passwd struct. All the salient references to it have been patched out. 

* I've noticed on a couple of occasions that if left running uninterrupted for two days, `smbd`'s CPU usage can skyrocket to a continuous 100%

* I've only tested `smbd`, the part of Samba that actually serves up files, and `testparm`. I've not tested `nmbd`, which announces your device's presence over NetBIOS, at all.

* Running this on a rooted phone would be best. Windows will only connect to SMB servers on port 445, a number certainly lower than 1024. 
That's not to say this is entirely useless if not rooted, however: you can `adb forward` port 4445 on your phone to 445 on a Windows loopback adapter, allowing you to access your shares over USB. This allows you to open large files from your phone without needing to copy the file in its entirety to your PC - this was my impetus for looking into all this in the first place. 
Write access to your external SD card can be achieved if rooted by installing a Magisk module that enables that.

* This package installs a sample smbd.conf to `$PREFIX/share/doc/samba/smb.conf.example`, which can be copied by the user into `$PREFIX/etc/samba/smb.conf`. This smb.conf is what I use; however, the settings disabling encryption have been taken out. My smb.conf is very opinionated  and disables things people may prefer to have on. 

* Samba thinks the only UNIX user account that actually exists is root. As such, any Samba account created will map to root. This is fine to me because Termux is a single-user system anyway. This had to be done because with any account not root, Samba will throw up errors about permissions and disallow browsing and writing to shares, even if the user account `smbd` is running under has permissions to read and write.

    * This is achieved by using berserker's berserker.c to override `getpwnam` etc. While Samba has username mapping functionality built in, API 24 lacks some password functions that Samba requires anyway, so it was easier to continue using  berserker.c 

    * This may or may not cause problems with permissions if sharing, say, your Termux home directory. I don't actually know and nor have I tested as I use SFTP for everything else

* The WAF cross-compile answers come from my S10 running Android 9 with kernel 4.14.154

All I do after installing is add a user account for Samba: `smbpasswd -L -a $(id -un)`

---

<details><summary>My script to start `smbd`</summary>
<p>

This takes care of setting up logging to Termux's tmp directory, adding an iptables rule to redirect 445 to 4445, bumping up the allowed number of open files and cleaning up the files left on exit.

```
#!/data/data/com.termux/files/usr/bin/dash
# vim: filetype=sh
: "${PREFIX:=/data/data/com.termux/files/usr}"
: "${TMPDIR:=$PREFIX/tmp}"
SVC_DAEMON="$PREFIX/bin/smbd"
PID_DIR="$PREFIX/var/run/samba"
SMBD_PID_FILE="$PID_DIR/smbd.pid"

start() {
	local log_dir="$PREFIX/tmp/log/samba"
	local iptargs='PREROUTING -t nat -p tcp --dport 445 -j REDIRECT --to-port 4445'

	mkdir -p "$log_dir" "$PID_DIR"
	su -c "/system/bin/iptables -C $iptargs 2>/dev/null || /system/bin/iptables -A $iptargs"
	su -c "$PREFIX/bin/prlimit" --pid $$ --nofile=65536:65536
	#[ "$(testparm -s --parameter-name='enable core files' 2>/dev/null)" = Yes ] && su -c "$PREFIX/bin/prlimit" --pid $$ --core=unlimited:unlimited

	exec start-stop-daemon --start --quiet --oknodo --exec "$SVC_DAEMON" --pidfile "$SMBD_PID_FILE" --nicelevel -4 -- --foreground --option='max open files=65536' --log-stdout --log-basename="$log_dir" >/dev/null 2>&1
}

stop() {
	local smbd_pid
	if [ -f "$SMBD_PID_FILE" ]; then 
		read -r smbd_pid < "$SMBD_PID_FILE"
		rm -f "$SMBD_PID_FILE"
	fi
	if [ -n "$smbd_pid" ] && [ -d "/proc/$smbd_pid" ]; then
		start-stop-daemon --stop --quiet --pid "$smbd_pid"
	else
		start-stop-daemon --stop --quiet --exec "$SVC_DAEMON"
	fi
	if [ $? -eq 0 ]; then
		sleep 1
	fi
	find "$PREFIX/var/lock/samba/" ! -type d -delete
	find "$PREFIX/var/lib/samba/private/msg.sock/" -type s -exec dash -c 'grep -q "$1" /proc/net/unix || unlink "$1"' _ {} \;
}

case $0 in
	*-stop)
		stop >/dev/null 2>&1
		exit $?
	;;
esac

if test ! -t 0; then
	start
else
	am startservice -n com.termux/com.termux.app.TermuxService -a com.termux.service_execute -d com.termux.file:"$(realpath "$0")" --ez com.termux.execute.background true
fi

```

</p>
</details>

---

<details><summary>Accessing Samba shares over USB on Windows</summary>
<p>

A working ADB connection is required.

1. Set up Windows as per [this](https://www.nikhef.nl/~janjust/CifsOverSSH/Win10Loopback.html). The PuTTY stuff can be skipped.

2. Run adb.exe on your computer like this to have forwarded ports bind to all your PC's interfaces: `adb kill-server & adb -a nodaemon server start`. The Windows Firewall prompts can be cancelled

3. Make sure smbd is running on your phone. I have the following in a batch file to automatically run that script from above (requires a rooted phone):

```
adb shell su -c "'x(){ am startservice -n com.termux/com.termux.app.TermuxService -a com.termux.service_execute -d com.termux.file:\"/data/data/com.termux/files/home/.shortcuts/tasks/smbd-start\" --ez com.termux.execute.background true; } ; x || { magiskpolicy --live \"allow system_server magisk_file sock_file read\" \"allow system_server magisk_file sock_file write\" ; x; }'"
if NOT "%ERRORLEVEL%"=="0" exit /b 1
```

4. Forward the port: `adb forward tcp:44445 tcp:4445`

5. Map the share: `net use Y: \\10.255.255.1\<name of share> <password> /USER:<name of samba user> /PERSISTENT:NO`

</p>
</details>

### CODE REVIEW

**Comment by Grimler91** [comment]
Nice! I updated the module and rebased the PR against master. 

For future reference the termux-packages submodule can be updated with `git submodule update --init --remote; git add termux-packages; git commit`

**Comment by qwerty12** [comment]
Will remember that, thanks @Grimler91!

**Comment by xeffyr** [comment]
For unknown reason latest Docker image doesn't have libparse-yapp-perl, heimdal-multidev, comerr-dev installed. I'm rebuilding it myself now and will upload to hub.docker.com.

Samba package will be built locally too.

**Comment by xeffyr** [comment]
> For unknown reason latest Docker image doesn't have libparse-yapp-perl, heimdal-multidev, comerr-dev installed

Was just a typo, fixed in https://github.com/termux/termux-packages/commit/ec53dbd4f04c112114c1544ed00a75e2fa120592.

**Comment by qwerty12** [comment]
Thanks for fixing it, @xeffyr

**Pull request merged**
