### PR TITLE
Bump libopenfec and roc versions

### PR DESCRIPTION
**Pull request by gavv**
* Update to libopenfec 1.4.2.4. The new version already includes android patch, so it is removed.

* Update to roc 0.1.1. The new version, among other things, already includes fixes for android, so the patches are removed.

See details in https://github.com/roc-project/roc/issues/222

### CODE REVIEW

**Comment by gavv** [comment]
@xeffyr will be deb package for roc updated automatically or some manual actions are needed? I see that [libopenfec](https://bintray.com/xeffyr/unstable-packages-24/libopenfec) was updated but [roc](https://bintray.com/xeffyr/unstable-packages-24/roc) wasn't. Is this because it's in manual-packages?

**Comment by xeffyr** [comment]
> some manual actions are needed?

Yes, it should be built manually because pulseaudio build directory should be present. Automatic builds download prebuilt dependencies directly from APT repository.

**Comment by gavv** [comment]
Thanks. What do you think about adding pulseaudio build directory to libpulseaudio-dev package? Probably only `.h` and `.so` files. If I understand correctly, this would allow us to fix this?

**Comment by xeffyr** [comment]
\*.so files are distrubuted in libpulseaudio and headers are in libpulseaudio-dev. So problem here only if roc uses some private stuff which is only available inside build directory.

The whole build directory is not a subject for packaging though.

**Comment by gavv** [comment]
> *.so files are distrubuted in libpulseaudio and headers are in libpulseaudio-dev. So problem here only if roc uses some private stuff which is only available inside build directory.

Exactly, Roc needs private headers because PulseAudio does not provide official public API for modules, only for clients. So I'm talking about packaging this private headers in libpulseaudio-dev, e.g. in a separate directory like `<prefix>/usr/lib/pulseaudio/build` or something.

**Pull request merged**
