### PR TITLE
Update installer.sh

### PR DESCRIPTION
**Pull request by roalyr**
`cpanm` didn't work for some reason, but `cpan install` did the job and biber compilled (I edited the script with nano like in this PR), please check.

P.S.: in fact I didn't remove `cpan install App::cpanminus` when I was installing, but that line seems redundant here.

### CODE REVIEW

**Comment by Grimler91** [comment]
Hey, thanks, cpanm is still used here: https://github.com/termux/unstable-packages/blob/914ef46c1a842781299cc8f44f7e5f4be260e899/packages/biber/installer.sh#L59 so that line need to be changed as well. 

Which arch have you tested on? See https://github.com/termux/termux-packages/issues/5638 for why installation fails on some arches

**Comment by roalyr** [comment]
My issue was trivial, it said "no cpanm bin found", so I've googled it and figured out a workaround that somehow worked (I still might not understand if doing `cpan install` is in any way detrimental to `cpanm`).

I am on aarch64

**Comment by Grimler91** [comment]
> My issue was trivial, it said "no cpanm bin found"

That's weird, does `cpan install App::cpanminus` fail for you? Or has cpanm been installed to `~/perl5/bin/` instead of `$PREFIX/bin`? `cpan install` is just less sophisticated than `cpanm`  but I haven't tested the installer with it.

It would be better to figure out why cpanm did not install properly for you, rather than switching to cpan

**Comment by roalyr** [comment]
Wow, it indeed is installed and can be called.
Maybe it has something to do with me using `fish` shell? I don't remember for sure if I have restarted the session since I was at the work then, but could it have been some failure in sourcing it?

**Comment by roalyr** [comment]
Screenshot_20200808_170034

**Comment by Grimler91** [comment]
I haven't tested the installer with fish so might be the reason. I don't see where in the script the issue would be (the script is run with bash anyways), so I have to investigate in a fresh PREFIX with fish.

**Comment by enigm4s** [comment]
I've never tried the installer,
I just use :
```
curl -L https://cpanmin.us | perl - App::cpanminus
```

maybe if this work, I'll use the installer.
aarch64 7.1

```
[$]► find ~/.. -name cpanm
/data/data/com.termux/files/home/../home/.cpan/build/App-cpanminus-1.7044-0/bin/cpanm
/data/data/com.termux/files/home/../home/.cpan/build/App-cpanminus-1.7044-0/blib/script/cpanm
/data/data/com.termux/files/home/../home/.cpanm/work/1596843706.11953/App-cpanminus-1.7044/bin/cpanm
/data/data/com.termux/files/home/../home/.cpanm/work/1596843706.11953/App-cpanminus-1.7044/blib/script/cpanm
/data/data/com.termux/files/home/../usr/bin/cpanm
```

**Comment by Grimler91** [comment]
I have verified that the installer does not work under fish. 
Now I just have to figure out how to fix it..

**Comment by roalyr** [comment]
Maybe it has to do with exporting / updating the session (because it worked after restarting it).

**Pull request closed without merging**
